project:
  type: website

website:
  title: "Theoretical Edge"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    math: katex
    theme:
      # - bootstrap
      - custom.scss
    # mainfont: 'Open Sans'
    # monofont: 'Fira Code'

