project:
  type: website

website:
  title: "Theoretical Edge"
  navbar:
    right:
      - about.qmd
    # left:
    #   - text: "Posts"
    #     href: posts/index.qmd
  page-navigation: true

metadata-files:
  - _metadata.yml

format:
  html:
    math: katex
    theme: simplex
    mainfont: 'Open Sans'
    monofont: 'Fira Code'

