---
title: "Black-Scholes Delta and the Risk-Neutral Measure"
format: html
execute:
  echo: true
  warning: false
---

## The Delta
I assume most readers are familiar with expression for the delta of a call option within the Black-Scholes model:

$$
\Delta = \frac{\partial C(K,T)}{\partial S} = N(d_1)
$$ {#eq-bs-delta}

where $C(K,T)$ is the price of a call option with strike $K$ and maturity $T$, on an asset with price $S$, $N(x)$ is the cumulative distribution function of the standard normal distribution, and $d_1$ is given by

$$
d_1 = \frac{\ln(S/K) + (r + \sigma^2/2)T}{\sigma\sqrt{T}}.
$$

The derivation of this formula, starting from the Black-Scholes call option price, is accessible to any STEM undergraduate, with a few pieces of paper (go on, try it!).

Beginning with the Black-Scholes call option price,

$$
C(K,T) = S_{0} N(d_{1}) - Ke^{-rT} N(d_{2}),
$$

differentiate once with respect to $S_{0}$ to get the delta:

$$
\begin{align}
\Delta C(K,T) &= \frac{ \partial }{ \partial S_{0} }  C(K,T) \\
&= \frac{ \partial  }{ \partial S_{0} } S_{0} N(d_{1}) 
- \frac{ \partial  }{ \partial S_{0} } Ke^{-rT} N(d_{2}) \\
&= N(d_{1}) 
+ S_{0}\frac{ \partial  }{ \partial S_{0} } N(d_{1}) 
- Ke^{-rT} \frac{ \partial }{ \partial S_{0} } N(d_{2}).
\end{align}
$$

I will leave it to you to show that
$$
\begin{align}
\frac{ \partial  }{ \partial S_{0} } N(d_{1})
= \frac{\phi(d_{1})}{S_{0} \sigma \sqrt{T}}
&&
\text{and}
&&
\frac{ \partial  }{ \partial S_{0} } N(d_{2})
= \frac{\phi(d_{2})}{S_{0} \sigma \sqrt{T}} 
\end{align}
$$

for $\phi(\cdot)$ the probability density function of the standard normal distribution.

But, working backwards from @eq-bs-delta, we still need to show
$$
\frac{\phi(d_{1})}{\sigma \sqrt{T}} = Ke^{-rT} \frac{\phi(d_{2})}{S_{0} \sigma \sqrt{T}}.
$$

With enough elbow grease, you can do the algebra and make it work out, but this actually has a much more elegant statement as the fact that $\frac{Ke^{-rT}}{S_{0}}$ is Radon-Nikodym derivative of the risk-neutral measure with respect to the stock-numeraire measure.

Let's break this down.

## Risk-Neutral Measure

Define two assets $S_t$ and $B_t$, with dynamics
$$
dS_t = \mu S_t \, dt + \sigma S_t \, dW_t 
$$
and
$$
dB_t = r B_t \, dt \quad \implies \quad B_t = e^{rt},
$$
where $W_t$ is a standard Brownian motion under the physical measure $\mathbb{P}$.

Defien the discounted stock asset $\bar{S}_t$ as
$$
\bar{S}_t = \frac{S_t}{B_t} = e^{-rt} S_t.
$$

Recall Itô's lemma:

::: {.theorem #thm-ito}
**Itô's Lemma**

Let $X_t$ be an Itô process given by
$$
dX_t = \mu(X_t, t) \, dt + \sigma(X_t, t) \, dW_t,
$$

then for any function $f(X_t, t)$ that is twice differentiable with respect to $X_t$ and once differentiable with respect to $t$, we have
$$
df(X_t, t) = \left( \frac{\partial f}{\partial t} + \mu \frac{\partial f}{\partial X_t} + \frac{1}{2} \sigma^2 \frac{\partial^2 f}{\partial X_t^2} \right) dt + \sigma \frac{\partial f}{\partial X_t} dW_t.
$$
:::

Apply @thm-ito to $\bar{S}_t$ to get

$$
\begin{align}
d\bar{S}_t 
&= \left( \frac{\partial \bar{S}_t}{\partial t} + \mu S_t \frac{\partial \bar{S}_t}{\partial S_t} + \frac{1}{2} \left( \sigma S_t \right)^2 \frac{\partial^2 \bar{S}_t}{\partial S_t^2} \right) dt + \sigma S_t \frac{\partial \bar{S}_t}{\partial S_t} dW_t \\
&= \left( \mu - r \right) \bar{S}_t \, dt + \sigma \bar{S}_t \, dW_t.
\end{align}
$$

If we define a new Brownian motion $W_t^\mathbb{Q}$ as
$$
dW_t^\mathbb{Q} = dW_t + \frac{\mu - r}{\sigma} \, dt,
$$
then we can rewrite the dynamics of $\bar{S}_t$ as
$$
d\bar{S}_t = \left( \mu - r \right) \bar{S}_t \, dt + \sigma \bar{S}_t \, \left( dW_t^\mathbb{Q} - \frac{\mu - r}{\sigma} \, dt \right).
$$




